
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[409] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  117,  117,
        0,    0,  127,  126,  123,   48,  116,  125,   28,   43,
       16,   17,   18,   44,   45,   23,   46,   15,   27,  112,
      112,   25,   40,   32,    1,   33,   49,   13,  125,   21,
       22,   36,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,   19,   39,
       20,   47,  117,  118,  126,  122,  122,  123,   35,  105,
      125,    6,   38,   10,    0,    0,    4,   41,    2,   42,
        3,   14,    0,  113,  106,  120,  124,    5,  113,  112,
      125,  125,  125,  112,  125,  125,  112,  125,   26,    0,

        0,    0,   29,   30,  103,   34,   31,  104,    0,    0,
        0,    0,  107,   11,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,   62,  125,  125,  125,  125,  125,
      125,  125,  125,   73,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,   12,   37,  117,    0,  121,  119,   24,
      113,  113,    0,  113,    0,  124,  113,  112,    0,  114,
        0,  112,  112,  125,  110,  103,    7,    8,    0,    0,
      109,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,   71,

      125,  125,  125,   77,  125,  125,   81,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,   99,  125,  125,  125,    0,  113,  113,
        0,  112,  125,  114,  114,  114,  114,  125,    0,  112,
      125,    9,    0,    0,  125,  125,  125,  125,   54,   55,
      125,   57,  125,  125,  125,  125,  125,   64,   65,  125,
      125,  125,  125,   72,  125,  125,  125,  125,   79,  125,
       82,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,   94,  125,  125,   98,  100,  125,  125,  113,
        0,  114,  114,  114,    0,    0,    0,    0,    0,  108,

      125,  125,  125,   53,   56,   58,   59,  125,  125,  125,
      125,   67,   68,   70,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,   88,  125,  125,   91,  125,  125,
       95,  125,  125,  102,    0,  115,    0,  125,   51,  125,
      125,  125,   63,  125,  125,  125,   75,  125,  125,   80,
      125,  125,  125,   86,   87,   89,  125,   92,  125,   96,
      125,  125,  115,  115,  115,    0,    0,  125,   52,  125,
       61,   66,   69,  125,  125,  125,   83,   84,  125,  125,
      125,  125,  125,    0,   50,   60,  125,  125,  125,  125,
       90,  125,  125,  101,    0,  125,  125,   78,   85,  125,

       97,  111,   74,   76,  125,  125,   93,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   30,   32,   33,   34,
       35,   35,   35,   35,   35,   36,   35,   35,   35,   37,
       35,   35,   35,   35,   35,   35,   35,   38,   35,   35,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   35,   53,   54,   55,   56,
       57,   58,   35,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    2,    3,    2,    1,    4,    5,    1,    2,    6,
        1,    1,    1,    1,    2,    1,    2,    1,    7,    7,
        7,    7,    1,    1,    2,    2,    2,    2,    1,    7,
        7,    7,    7,    7,    8,    8,    9,    8,    2,    1,
        2,    1,    9,    7,    7,    7,    7,    7,    7,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[419] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   66,   67,
       71,   72,  763,  764,   74,  736,  755,    0,  734,   70,
      719,  764,  764,  732,   66,  764,   67,   69,   69,   91,
       83,  734,  764,  115,  730,   73,  764,  128,  745,  147,
      764,  728,   99,  105,  125,  106,  127,  113,  115,  142,
      128,  145,  143,  110,  150,  158,  133,  123,  764,  135,
      764,  764,  713,  764,  172,  764,  734,  192,  764,  764,
        0,  764,  764,  764,  137,  163,  764,  764,  764,  764,
      764,  764,  734,  199,  764,  764,    0,  764,  203,  196,
      234,  180,  243,    0,  272,  247,  252,  256,  764,  281,

      307,  202,  254,  764,  296,  764,  764,  212,  294,  694,
      709,  241,  731,  764,  687,  686,  688,  696,  682,  226,
      698,  697,  684,  690,  676,  677,  674,  674,  680,  677,
      675,  672,  669,    0,  671,  252,  672,  666,  662,  671,
      678,  151,  678,  661,  664,  171,  662,  667,  662,  272,
      270,  132,  665,  764,  764,  676,  207,  764,  764,  764,
        0,  764,  319,  283,  306,    0,  323,  328,  331,  336,
        0,  369,  341,  353,  764,  350,  764,  764,  689,  653,
      696,  651,  663,  656,  665,  660,  659,  660,  646,  644,
      320,  659,  657,  653,  645,  651,  638,  653,  652,    0,

      638,  338,  633,  645,  642,  639,    0,  636,  636,  625,
      626,  632,  623,  625,  622,  630,  633,  619,  633,  618,
      620,  620,  627,    0,  627,  629,  618,  385,  389,    0,
      405,  409,  400,  434,    0,    0,  346,  410,  403,    0,
      333,  764,  623,  653,  610,  609,  619,  613,    0,    0,
      614,    0,  604,  602,  610,  599,  606,    0,    0,  603,
      610,  603,  595,    0,  606,  587,  594,  572,    0,  567,
        0,  585,  579,  566,  532,  524,  521,  529,  534,  520,
      532,  526,    0,  512,  515,    0,    0,  513,  525,  450,
      466,  470,  764,  390,  486,  404,  502,  421,  513,  764,

      527,  509,  525,    0,    0,    0,    0,  512,  513,  518,
      518,    0,  505,    0,  502,  495,  496,  502,  502,  498,
      486,  500,  498,  486,    0,  495,  478,    0,  486,  477,
      475,  482,  468,    0,  454,  506,  466,  468,    0,  456,
      449,  449,    0,  443,  435,  452,    0,  452,  452,    0,
      447,  446,  419,    0,    0,    0,  429,    0,  410,    0,
      417,  406,  511,  764,  402,  542,  407,  389,    0,  391,
        0,    0,    0,  379,  385,  385,    0,    0,  382,  340,
      341,  338,  319,  319,    0,    0,  298,  280,  281,  254,
        0,  227,  199,    0,  201,  180,  177,    0,    0,   79,

        0,  764,    0,    0,   53,   50,    0,  764,  585,  594,
      603,  608,  617,  625,  634,  643,   74,  646
    } ;

static yyconst flex_int16_t yy_def[419] =
    {   0,
      408,    1,  409,  409,  409,  409,  409,  409,  410,  410,
      411,  411,  408,  408,  408,  408,  408,  412,  408,  408,
      413,  408,  408,  408,  408,  408,  408,  408,  408,  412,
       30,  408,  408,  414,  408,  408,  408,  408,  412,  408,
      408,  408,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  408,  408,
      408,  408,  415,  408,  415,  408,  408,  408,  408,  408,
      412,  408,  408,  408,  413,  413,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  416,  408,  408,   30,
       31,  412,  412,  412,  412,  412,   31,  412,  408,  414,

      408,  414,  414,  408,  414,  408,  408,  408,  408,  408,
      413,  408,  408,  408,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  408,  408,  415,  415,  408,  408,  408,
       84,  408,  408,  408,  408,  416,   84,  412,  408,  412,
      417,   31,   31,  412,  408,  414,  408,  408,  408,  408,
      408,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  408,  408,  167,
      408,  412,  412,  408,  170,  412,  412,  170,  418,  172,
      172,  408,  408,  408,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  408,
      408,  408,  408,  408,  408,  418,  408,  418,  408,  408,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  408,  408,  408,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  408,  408,  408,  408,  408,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  408,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  408,  412,  412,  412,  412,  412,

      412,  408,  412,  412,  412,  412,  412,    0,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408
    } ;

static yyconst flex_int16_t yy_nxt[836] =
    {   0,
       14,   15,   15,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       31,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   40,   14,
       41,   42,   39,   43,   44,   45,   46,   47,   48,   49,
       39,   50,   39,   51,   39,   52,   39,   53,   54,   55,
       56,   39,   57,   58,   39,   39,   39,   59,   60,   61,
       62,   64,   64,   14,   14,   68,   68,   68,   73,   78,
      239,   86,   80,   67,   67,   83,   87,   84,   84,   84,
       84,   79,   81,   82,   88,   74,  407,   85,  107,  108,

      406,   97,   97,   97,   97,   65,   65,   89,  111,   90,
       90,   90,   91,   71,  111,  111,  100,  100,  101,  111,
       71,   92,  111,   93,  111,   98,   94,   71,   95,  109,
      109,  109,  111,   96,  111,   92,  111,  111,   93,  103,
      104,  105,  111,  115,   94,  405,  159,   71,  112,  112,
      112,  111,  111,  124,  111,   95,  129,  144,  116,  111,
      154,  117,  125,  118,  130,  408,  131,  111,  120,  132,
      119,  133,   75,  153,  408,  121,   76,  156,  122,  110,
      126,  123,  127,  225,  137,  226,  141,  113,  138,  152,
      134,  128,  139,   68,   68,   68,  135,  136,  168,  168,

      145,  142,  210,  155,  143,  408,  140,  211,  150,  408,
      146,  147,  156,  148,  215,  149,  151,  161,  161,  161,
      161,  167,  167,  167,  167,  404,   71,  408,  176,  216,
      162,  163,  164,   71,  162,  163,  164,  178,  179,  403,
       71,  165,  112,  112,  112,  162,  163,  164,  402,  162,
      163,  164,   91,   91,   91,   91,  169,  408,  169,  401,
       71,  170,  170,  170,  170,   90,   90,   90,   91,   71,
      173,  173,  173,  173,   91,   91,   91,   91,  400,  177,
      176,  113,  100,  100,  101,  187,  188,   71,  171,   96,
      172,  172,  172,  172,  174,  109,  109,  109,   98,  408,

      399,  172,  172,  172,  172,  172,  408,  105,  101,  101,
      101,  203,  204,  222,  162,  172,  172,  172,  172,  172,
      172,  408,  176,  220,  161,  161,  161,  161,  398,  162,
      221,  223,  228,  175,  228,  224,  397,  229,  229,  229,
      229,  230,  230,  230,  230,  110,  232,  232,  165,  234,
      234,  234,  234,  408,  235,  235,  235,  235,  396,  173,
      173,  173,  173,   94,  395,  231,  394,  236,   71,  237,
      233,  173,  173,  173,  173,  408,  176,  236,  238,  254,
      255,   94,  236,  174,  237,  408,   71,  240,  240,  240,
      240,  265,  236,  393,  266,  174,  392,  391,  240,  240,

      240,  240,  240,  229,  229,  229,  229,  290,  290,  290,
      290,  241,  240,  240,  240,  240,  240,  240,  232,  232,
      162,  293,  164,  230,  230,  230,  230,  232,  232,  390,
      389,  291,  388,  364,  387,  162,  293,  164,  386,  297,
      297,   71,  233,   71,   94,  298,  298,  231,  364,  385,
      384,  233,  292,  292,  292,  292,   71,  408,   71,  383,
      297,  297,   94,  298,  382,  293,  381,  294,  290,  290,
      290,  290,  336,  336,  336,  336,  295,  380,  408,  379,
      293,  162,  294,  164,  290,  290,  290,  290,  292,  292,
      292,  292,  291,  378,  377,  376,  162,  375,  164,  374,

      373,  293,  372,  294,  292,  292,  292,  292,  291,  371,
      370,  369,  295,  368,  367,  335,  293,  335,  294,  362,
      336,  336,  336,  336,  363,  363,  363,  363,  295,  363,
      363,  363,  363,  361,  360,  359,  358,  364,  357,  365,
      356,  355,  364,  354,  365,  353,  352,  351,  366,  350,
      349,  348,  364,  366,  365,  347,  346,  364,  345,  365,
      363,  363,  363,  363,  344,  343,  342,  341,  340,  339,
      338,  337,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  366,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   71,  322,   71,   71,   71,   75,   75,   75,
       75,   75,  321,   75,   75,   75,  102,  102,  320,  319,
      318,  102,  102,  102,  156,  156,  156,  317,  156,  156,
      156,  156,  156,  166,  166,  316,  166,  166,  166,  166,
      166,  166,  296,  315,  296,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  264,  263,  262,  261,  260,  259,

      258,  257,  256,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  157,  227,  219,  218,  217,
      214,  213,  212,  209,  208,  207,  206,  205,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  186,  185,  184,  183,  182,  181,   76,  180,
      160,  158,  157,  114,  111,  106,   99,   77,   76,   72,
       70,   69,  408,   13,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408
    } ;

static yyconst flex_int16_t yy_chk[836] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   10,   11,   12,   15,   15,   15,   20,   25,
      417,   29,   27,   11,   12,   28,   29,   28,   28,   28,
       28,   25,   27,   27,   29,   20,  406,   28,   36,   36,

      405,   31,   31,   31,   31,    9,   10,   30,   43,   30,
       30,   30,   30,   31,   44,   46,   34,   34,   34,   54,
       31,   30,   48,   30,   49,   31,   30,   31,   30,   38,
       38,   38,   58,   30,   45,   30,   47,   51,   30,   34,
       34,   34,   57,   43,   30,  400,   75,   31,   40,   40,
       40,   50,   53,   46,   52,   30,   48,   54,   43,   55,
       60,   44,   46,   44,   48,   76,   48,   56,   45,   48,
       44,   49,   76,   58,   65,   45,   75,   65,   45,   38,
       47,   45,   47,  152,   51,  152,   53,   40,   52,   57,
       50,   47,   52,   68,   68,   68,   50,   50,   92,   92,

       55,   53,  142,   60,   53,  102,   52,  142,   56,  157,
       55,   55,  157,   55,  146,   55,   56,   84,   84,   84,
       84,   89,   89,   89,   89,  397,   90,  102,  102,  146,
       84,   84,   84,   90,   89,   89,   89,  108,  108,  396,
       90,   84,  112,  112,  112,   84,   84,   84,  395,   89,
       89,   89,   91,   91,   91,   91,   93,  103,   93,  393,
       90,   93,   93,   93,   93,   96,   96,   96,   96,   91,
       97,   97,   97,   97,   98,   98,   98,   98,  392,  103,
      103,  112,  100,  100,  100,  120,  120,   91,   95,   96,
       95,   95,   95,   95,   97,  109,  109,  109,   98,  105,

      390,   95,   95,   95,   95,   95,  100,  100,  101,  101,
      101,  136,  136,  151,  164,   95,   95,   95,   95,   95,
       95,  105,  105,  150,  165,  165,  165,  165,  389,  164,
      150,  151,  163,  101,  163,  151,  388,  163,  163,  163,
      163,  167,  167,  167,  167,  109,  168,  168,  165,  169,
      169,  169,  169,  176,  170,  170,  170,  170,  387,  173,
      173,  173,  173,  168,  384,  167,  383,  170,  241,  170,
      168,  174,  174,  174,  174,  176,  176,  237,  170,  191,
      191,  168,  170,  173,  170,  172,  241,  172,  172,  172,
      172,  202,  237,  382,  202,  174,  381,  380,  172,  172,

      172,  172,  172,  228,  228,  228,  228,  229,  229,  229,
      229,  172,  172,  172,  172,  172,  172,  172,  233,  233,
      229,  294,  229,  231,  231,  231,  231,  232,  232,  379,
      376,  229,  375,  365,  374,  229,  294,  229,  370,  239,
      296,  238,  233,  238,  232,  239,  296,  231,  365,  368,
      367,  232,  234,  234,  234,  234,  238,  298,  238,  362,
      239,  296,  232,  298,  361,  234,  359,  234,  290,  290,
      290,  290,  335,  335,  335,  335,  234,  357,  298,  353,
      234,  290,  234,  290,  291,  291,  291,  291,  292,  292,
      292,  292,  290,  352,  351,  349,  290,  348,  290,  346,

      345,  292,  344,  292,  295,  295,  295,  295,  291,  342,
      341,  340,  292,  338,  337,  297,  292,  297,  292,  333,
      297,  297,  297,  297,  336,  336,  336,  336,  295,  363,
      363,  363,  363,  332,  331,  330,  329,  336,  327,  336,
      326,  324,  363,  323,  363,  322,  321,  320,  336,  319,
      318,  317,  336,  363,  336,  316,  315,  363,  313,  363,
      366,  366,  366,  366,  311,  310,  309,  308,  303,  302,
      301,  299,  289,  288,  285,  284,  282,  281,  280,  279,
      278,  277,  276,  275,  366,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  412,  274,  412,  412,  412,  413,  413,  413,
      413,  413,  273,  413,  413,  413,  414,  414,  272,  270,
      268,  414,  414,  414,  415,  415,  415,  267,  415,  415,
      415,  415,  415,  416,  416,  266,  416,  416,  416,  416,
      416,  416,  418,  265,  418,  263,  262,  261,  260,  257,
      256,  255,  254,  253,  251,  248,  247,  246,  245,  244,
      243,  227,  226,  225,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      206,  205,  204,  203,  201,  199,  198,  197,  196,  195,

      194,  193,  192,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  156,  153,  149,  148,  147,
      145,  144,  143,  141,  140,  139,  138,  137,  135,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  119,  118,  117,  116,  115,  113,  111,  110,
       83,   67,   63,   42,   39,   35,   32,   24,   21,   19,
       17,   16,   13,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[127] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 
    0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java8.l"
#line 2 "java8.l"
#include <stdio.h>
#include <stdlib.h>
#include "y.tab.h"

int yywrap(void) {
  return 1;
}






#line 811 "lex.yy.c"

#define INITIAL 0
#define INTEGER_LITERAL 1
#define FLOATING_LITERAL 2
#define CHARACTER_LITERAL 3
#define DOUBLE_STRING 4
#define B_COMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 52 "java8.l"

#line 1000 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 409 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 764 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "java8.l"
return '=';
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 54 "java8.l"
return AADD;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 55 "java8.l"
return ASUB;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "java8.l"
return AMUL;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "java8.l"
return ADIV;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "java8.l"
return AMOD;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "java8.l"
return ALEFTSHIFT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "java8.l"
return ARIGHTSHIFT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "java8.l"
return ALOGICALRIGHTSHIFT;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "java8.l"
return ABITAND;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "java8.l"
return ABITXOR;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "java8.l"
return ABITOR;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "java8.l"
return '@';
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "java8.l"
return RARROW;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "java8.l"
return '.';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "java8.l"
return '\'';
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "java8.l"
return '(';
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "java8.l"
return ')';
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "java8.l"
return '{';
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "java8.l"
return '}';
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "java8.l"
return '[';
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "java8.l"
return ']';
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "java8.l"
return ',';
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "java8.l"
return VAR_LEN_PARAM;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "java8.l"
return ':';
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "java8.l"
return MR;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "java8.l"
return '/';
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "java8.l"
return '%';
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "java8.l"
return LEFTSHIFT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "java8.l"
return LTEQ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "java8.l"
return GTEQ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 "java8.l"
return '<';
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "java8.l"
return '>';
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "java8.l"
return EQ;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "java8.l"
return NE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "java8.l"
return '^';
	YY_BREAK
case 37:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 89 "java8.l"
return COMB_VB;
	YY_BREAK
case 38:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 90 "java8.l"
return COMB_AND;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "java8.l"
return NON_COMB_VB;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "java8.l"
return ';';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "java8.l"
return INC;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "java8.l"
return DEC;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "java8.l"
return NON_COMB_AND;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "java8.l"
return '*';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "java8.l"
return '+';
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "java8.l"
return '-';
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "java8.l"
return '~';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "java8.l"
return '!';
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "java8.l"
return '?';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "java8.l"
return ABSTRACT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "java8.l"
return ASSERT;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "java8.l"
return BOOLEAN_TYPE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "java8.l"
return BREAK;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "java8.l"
return BYTE_TYPE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "java8.l"
return CASE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "java8.l"
return CATCH;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "java8.l"
return CHAR_TYPE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "java8.l"
return CLASS;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "java8.l"
return CONST;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "java8.l"
return CONTINUE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "java8.l"
return DEFAULT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "java8.l"
return DO;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "java8.l"
return DOUBLE_TYPE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "java8.l"
return ELSE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "java8.l"
return ENUM;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "java8.l"
return EXTENDS;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "java8.l"
return FALSE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "java8.l"
return FINAL;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "java8.l"
return FINALLY;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 123 "java8.l"
return FLOAT_TYPE;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "java8.l"
return FOR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "java8.l"
return GOTO;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "java8.l"
return IF;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "java8.l"
return IMPLEMENTS;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "java8.l"
return IMPORT;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "java8.l"
return INSTANCEOF;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "java8.l"
return INT_TYPE;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "java8.l"
return INTERFACE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "java8.l"
return LONG_TYPE;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "java8.l"
return NATIVE;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "java8.l"
return NEW;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "java8.l"
return NULL_LITERAL;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "java8.l"
return PACKAGE;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "java8.l"
return PRIVATE;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "java8.l"
return PROTECTED;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "java8.l"
return PUBLIC;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "java8.l"
return RETURN;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "java8.l"
return SHORT_TYPE;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "java8.l"
return STATIC;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "java8.l"
return STRICTFP;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "java8.l"
return SUPER;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "java8.l"
return SWITCH;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "java8.l"
return SYNCHRONIZED;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "java8.l"
return THIS;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "java8.l"
return THROW;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "java8.l"
return THROWS;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "java8.l"
return TRANSIENT;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "java8.l"
return TRUE;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "java8.l"
return TRY;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "java8.l"
return VOID_TYPE;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "java8.l"
return VOLATILE;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "java8.l"
return WHILE;
	YY_BREAK
case 103:
/* rule 103 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 157 "java8.l"
{return TYPE_ARG_OP;}
	YY_BREAK
case 104:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 158 "java8.l"
{ return COMB_GT;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 159 "java8.l"
{ return STRING;}
	YY_BREAK
case 106:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 160 "java8.l"
{ return ANNO_DOT;}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 161 "java8.l"
{return E_DIM;}
	YY_BREAK
case 108:
/* rule 108 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 162 "java8.l"
{return E_DIM;}
	YY_BREAK
case 109:
/* rule 109 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 163 "java8.l"
{return E_DIM_DOT;}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 164 "java8.l"
{return E_DIAMOND;}
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 165 "java8.l"
{return ANNO_INTERFACE;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 167 "java8.l"
{return INT;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 169 "java8.l"
{return FLOAT;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 170 "java8.l"
{return FLOAT;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 171 "java8.l"
{return FLOAT;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 173 "java8.l"
{ BEGIN DOUBLE_STRING; }
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 174 "java8.l"
{ return STRING; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 175 "java8.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 177 "java8.l"
{ return CHAR; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 181 "java8.l"
{ BEGIN(B_COMMENT); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 182 "java8.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 183 "java8.l"
{ }
	YY_BREAK
case 123:
/* rule 123 can match eol */
YY_RULE_SETUP
#line 184 "java8.l"
{}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 186 "java8.l"
{}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 188 "java8.l"
{return IDENTIFIER;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 190 "java8.l"
ECHO;
	YY_BREAK
#line 1753 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INTEGER_LITERAL):
case YY_STATE_EOF(FLOATING_LITERAL):
case YY_STATE_EOF(CHARACTER_LITERAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(B_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 409 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 409 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 408);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 190 "java8.l"



