
typedef unsigned long int symbol_t;
#define _TBoolean ((symbol_t)1)
#define _TInt ((symbol_t)2)
#define _TString ((symbol_t)3)
#define _Name ((symbol_t)4)
#define _Param ((symbol_t)5)
#define _List ((symbol_t)6)
#define _Not ((symbol_t)7)
#define _Integer ((symbol_t)8)
#define _True ((symbol_t)9)
#define _False ((symbol_t)10)
#define _String ((symbol_t)11)
#define _Null ((symbol_t)12)
#define _Apply ((symbol_t)13)
#define _LessThan ((symbol_t)14)
#define _GreaterThan ((symbol_t)15)
#define _NotEquals ((symbol_t)16)
#define _Equals ((symbol_t)17)
#define _And ((symbol_t)18)
#define _Or ((symbol_t)19)
#define _Expression ((symbol_t)20)
#define _ExpressionStatement ((symbol_t)21)
#define _If ((symbol_t)22)
#define _Return ((symbol_t)23)
#define _Block ((symbol_t)24)
#define _VarDecl ((symbol_t)25)
#define _VarList ((symbol_t)26)
#define _Declaration ((symbol_t)27)
#define _Function ((symbol_t)28)
#define _Empty ((symbol_t)29)
#define _Source ((symbol_t)30)
#define MAXTAG 31
#define _type ((symbol_t)1)
#define _name ((symbol_t)2)
#define _list ((symbol_t)3)
#define _body ((symbol_t)4)
#define _expr ((symbol_t)5)
#define _recv ((symbol_t)6)
#define _left ((symbol_t)7)
#define _right ((symbol_t)8)
#define _cond ((symbol_t)9)
#define _then ((symbol_t)10)
#define _else ((symbol_t)11)
#define MAXLABEL 12
void* cello_parse(const char *text, size_t len, void *, void* (*fnew)(symbol_t, const char *, size_t, size_t, void *), void  (*fset)(void *, size_t, symbol_t, void *, void *), void  (*fgc)(void *, int, void *));
long cello_match(const char *text, size_t len);
const char* cello_tag(symbol_t n);
const char* cello_label(symbol_t n);
